name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # 你的主分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 或你的版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate thumbnails
        run: python ./generate_thumbs.py

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Build static site
        run: |
          python manage.py distill-local output --force

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
